### PR TITLE
Ft signup page

### PR DESCRIPTION
**Pull request by martinemahirwe**
### What does this PR do?

- Adds sign Up  page with responsiveness

### Description of Task to be completed

- Creating place to enter identifications

- making responsive webdesigns for 4 different css breakpoints

### How should this manually be tested?

- Download this repo and open `sign.html `

### CODE REVIEW

**Review by wakaflorien — CHANGES_REQUESTED** [review]
- Form needs some UI improvements like input width, inside padding and spacing between inputs
- be consistent with the margins of the header.
Screenshot from 2023-06-06 08-50-52

**Review by wakaflorien — CHANGES_REQUESTED** [review]
- Age should be an input not a span
image

**Review by wakaflorien — COMMENTED** [review]
- Resolve conflicts

**Review by wakaflorien — APPROVED** [review]

**Comment by martinemahirwe** [comment]
i'm having trouble about add article, it's difficult to give it same form
as messages or manage articles,,, is it mandatory to give them same form???
add new article requires to enter info but others they don't; how am i
going to give them same form??? even in tutorial i watched they give add
article inputs, and messages and manage articles table like form

**Pull request merged**
