### PR TITLE
Ft login page

### PR DESCRIPTION
**Pull request by martinemahirwe**
### What does this PR do?

- Adds log in page with iresponsiveness

### Description of Task to be completed

- Creating log in 
- making responsive webdesigns for 4 different css breakpoints

### How should this manually be tested?

- Download this repo and open `log.html `

### CODE REVIEW

**Review by wakaflorien — CHANGES_REQUESTED** [review]
- same here

**Review by wakaflorien — CHANGES_REQUESTED** [review]
- on Large screen the title dissapears
-
image

**Comment by martinemahirwe** [comment]
let me check

**Comment by martinemahirwe** [comment]
my responsiveness

**Comment by wakaflorien** [comment]
[image: image.png]
Please resolve all of those conflicts

**Review by wakaflorien — APPROVED** [review]

**Pull request merged**
